### ISSUE TITLE
dodavanje platformi u level

### ISSUE THREAD

**Issue by landrasic21** [AILab-FOI/PRRI-HoloGameV2024#13]
Potrebno je organizirati platforme na koje će igrač moći skakati. Treba se uzeti u obzir daljina na koju igrač može skočiti. Također, treba dizajnirati podnožje (pod) i na njemu također postaviti neke prepreke.

Platforme su za sada objekti tipa _rect_ u kodu i trebaju biti definirani putem map editora.
Za detalje pogledati #12 zadatak (klikni na link). 

### Napomena
Nije potrebno baviti se kodom i sudaranjim au objekte!

**Comment by dprimorac21foi** [comment]
Ovako sam zamislio dizajn levela sa platformama i pozadinom ako netko misli da nešto treba promjeniti slobodno javi.

![hologame-level 1](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/162130728/fe1f1b53-a642-456f-ad77-53723eee1ded)
![sdfsdgsd](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/162130728/7aec3a6f-e7f5-4dd4-8d9d-a60b4ec7e025)
![Snimka zaslona 2024-05-06 203826](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/162130728/96518a5f-768e-4570-9603-8bad6f680763)
![Snimka zaslona 2024-05-06 203904](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/162130728/1e027126-2adc-41ef-8297-58128354591a)
![Snimka zaslona 2024-05-06 203927](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/162130728/185bbe97-a3a9-48f2-a718-43bb119f9649)
![Snimka zaslona 2024-05-06 204011](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/162130728/2138234b-c2bf-446e-abe6-3860ba896c4a)
