### ISSUE TITLE
🚯 Prvi level ima viška tiles

### ISSUE THREAD

**Issue by dmatijani** [AILab-FOI/PRRI-HoloGameV2024#54]
Prvi level ima kod praznina postavljene prozirne _tiles_, koji se smatraju kao kolizije, dok zapravo svi prozirni trebaju biti element s indeksom 0:
![image](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/126497251/fe670d41-9b50-40d6-8948-facb712f6f29)

Treba sve postaviti da su ovaj element u gore lijevom čošku.

**Comment by mmarkoovin21** [comment]
# Napomena
`bundle.py` konstantno overwritea `hologame.py` tako da mu doda duplu `<tiles>` oznaku @dmatijani
