### ISSUE TITLE
Kreiranje HUD-a

### ISSUE THREAD

**Issue by landrasic21** [AILab-FOI/PRRI-HoloGameV2024#7]
Potrebno je kreirati HUD igrice koji će se vidjeti bez obzira na trenutni level igrača. 
Od informacija se moraju vidjet:

- [x]  životna traka 
- [x] trenutni level
- [x] oružje koje se trenutno koristi.

Koristan link:https://www.youtube.com/watch?v=UC6BII9IYoA&list=PLOUbntoMeucFBoxH6-AkpyHA2DJ5oBSPB&index=14

### Napomena
Još se nismo dogovorili kako će igrač napredovati kroz igricu i hoće li skupljati kakve bodove. Neka ideja koju ja osobno imam je broj metaka u šanžeru koje će igrač skopljati tokom igre. Ako imaš bolji prijedlog, javi!

**Comment by tivanovic21** [comment]
[HUD.zip](https://github.com/AILab-FOI/PRRI-HoloGameV2024/files/15092730/HUD.zip)
Dizajn HUD-a. Napravljen je inicijalni zaslon koji prikazuje level 16, 203HP-a (u dizajnu je igrač izgubio nešto HP-a zbog čega je životna traka različitih boja) i prikazuje odabrani blaster 1)

**Comment by tivanovic21** [comment]
@mmarkoovin21 treba li dodavati još verzija dizajna primjerice za sve vrste oružja ili mogu zatvoriti issue?
