### ISSUE TITLE
Kreirati dizajn igrača

### ISSUE THREAD

**Issue by landrasic21** [AILab-FOI/PRRI-HoloGameV2024#8]
Potrebno je kreirati ili pronaći dizajn igrača. Također je potrebno povezati sve animacije sa implementacijama unutar igrice.
Igrač treba imati ove animacije tj. slika za svaku od ovih radnji:

### Veličina igrača treba biti 16x16!
Također je bitno paziti na boje koj etic80 podržava: https://github.com/nesbox/TIC-80/wiki/palette

- [x] šetanje (2 sprite-a izmjenjivanja noge i ruke)
- [x] idle stanje
- [x] stanje damagea
- [x] skok
- [x] penjanje uz ljestve
- [x] pucanje iz blastera 1
- [x] pucanje iz blastera 2
- [x] pucanje iz blastera 3

Evo slika blastera pa da imaš referencu:
![image](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/126497369/2e543c83-d2bd-4008-9fa2-dcec3f0d28d7)

### Napomena
Nije potrebno raditi slike za obije strane jer se u kodu slika može okrenuti!
Kada završiš s dizajnom igrača pošalji ga @mmarkoovin21 da ga stavimo u jedan sprite kojeg ćemo importati!ž
Nakon što se svi spriteovi importaju, potrebno je iste primjeniti u kudu kako bi se prikazivali na određene radnje igrača (samo zamijeniti broj spritea u kodu i dodati _spr()_ funkciju na skok).
Korisna dokumentacija: https://github.com/nesbox/TIC-80/wiki/spr

Ako radiš spriteove sam, preporučam korištenje ovog alata:
https://www.piskelapp.com/p/create/sprite

**Comment by tivanovic21** [comment]
[mainchar.zip](https://github.com/AILab-FOI/PRRI-HoloGameV2024/files/15092718/mainchar.zip)
Dokumenti za dizajn glavnog lika (bez blastera 2 i 3, ne znam kako ih ukomponirati u dizajn lika bez da se narušava dizajn blastera ili lika)

**Comment by mmarkoovin21** [comment]
Evo napravila sam nešto po tom pitanju.
![sprites](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/126497369/3f7583f6-913f-48a4-b72a-48cde909b099)
Ovo je sata sprite svih likova i blastera u igrici.

Link na sliku: https://foi-my.sharepoint.com/:i:/g/personal/mmarkovin21_foi_hr/EboO_Kt9NblGrxZk8Wlr6gIBnsMfRuLjZtB3OByNJAFtxw?e=jHxl8Z


Bi li mogao ubaciti te spriteove u igricu na odgovarajuća mjesta?

**Comment by tivanovic21** [comment]
> Evo napravila sam nešto po tom pitanju.
> 
> ![sprites](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/126497369/3f7583f6-913f-48a4-b72a-48cde909b099)
> 
> Ovo je sata sprite svih likova i blastera u igrici.
> 
> 
> 
> Link na sliku: https://foi-my.sharepoint.com/:i:/g/personal/mmarkovin21_foi_hr/EboO_Kt9NblGrxZk8Wlr6gIBnsMfRuLjZtB3OByNJAFtxw?e=jHxl8Z
> 
> 
> 
> 
> 
> Bi li mogao ubaciti te spriteove u igricu na odgovarajuća mjesta?

Nisam radio do sad u tic-u, jer ga ne mogu instalirati na svom laptopu pa ako nije problem da ih ti ubaciš?

**Comment by mmarkoovin21** [comment]
moze

TODO:

- [ ] Napraviti izmjenu spriteova kod hodanja
- [ ] Napraviti izmjenu spriteova kod penjaja(implementirati penjanje)
- [ ] Napraviti izmjenu spriteova kod pucanja
